# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjaDmnsCAP-sMCC2qNs2w9xSIQfeNp3k
"""

pip install streamlit

import streamlit as st

# Title
st.title("Simple Streamlit App")

# Text input
user_input = st.text_input("Enter some text", "Type here...")

# Display the input
st.write("You entered:", user_input)

